openapi: 3.0.0

info:
  title: Todo API
  description: Api for managing todos
  version: 1.0.0

paths:
  /:
    get:
      summary: Get API information
      operationId: getApiInfo
      responses:
        '200':
          description: API information
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The current operational status of the API
                    example: 'operational'
                  uptime:
                    type: integer
                    format: int64
                    description: The amount of time the API has been running
                    example: 11.123456789
                  contact:
                    type: object
                    description: Contract information for API support
                    properties:
                      email:
                        type: string
                        example: 'support@example.com'
                      website:
                        type: string
                        example: 'https://example.com'
                  documentation:
                    type: string
                    description: Link to this API's documentation
                    example: 'http://api.example.com/docs'
                  license:
                    type: string
                    description: The license type of the API
                    example: 'MIT'
                  server_time:
                    type: string
                    description: The current time of the API
                    example: '2024-01-01T00:00:00Z'
        '500':
          description: Server error
